/**
 * Seed the election_services table with per-state voter registration and
 * ballot tracking information for all 50 states + DC.
 *
 * Data is maintained as a static map.  Each record is keyed by two-letter
 * state abbreviation and mapped to the corresponding state jurisdiction_id
 * via a slug lookup at runtime.
 *
 * Run with:  npm run import:election-services
 */

import { supabase } from './lib/supabase-admin.js';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface ElectionServiceDefinition {
  /** Two-letter postal abbreviation, used only for logging. */
  abbr: string;
  /** Must match jurisdictions.slug in the database. */
  jurisdictionSlug: string;
  election_office_name: string;
  registration_url: string;
  /** URL to check existing voter registration status (may be same as registration_url). */
  registration_status_url: string | null;
  has_online_registration: boolean;
  ballot_tracking_url: string | null;
  has_ballot_tracking: boolean;
  election_office_phone: string | null;
  election_office_email: string | null;
  election_office_address: string | null;
  /** Free-form notes on registration requirements. */
  requirements: string | null;
}

interface ElectionServiceInsert {
  jurisdiction_id: string;
  election_office_name: string;
  registration_url: string;
  registration_status_url: string | null;
  has_online_registration: boolean;
  ballot_tracking_url: string | null;
  has_ballot_tracking: boolean;
  election_office_phone: string | null;
  election_office_email: string | null;
  election_office_address: string | null;
  requirements: string | null;
}

// ---------------------------------------------------------------------------
// Static data — 50 states + DC
// ---------------------------------------------------------------------------

const ELECTION_SERVICES: ElectionServiceDefinition[] = [
  {
    abbr: 'AL',
    jurisdictionSlug: 'alabama',
    election_office_name: 'Alabama Secretary of State — Elections Division',
    registration_url: 'https://myinfo.alabamavotes.gov/VoterView/RegistrantSearch.do',
    registration_status_url: 'https://myinfo.alabamavotes.gov/VoterView/RegistrantSearch.do',
    has_online_registration: true,
    ballot_tracking_url: 'https://myinfo.alabamavotes.gov/VoterView/AbsenteeBallotSearch.do',
    has_ballot_tracking: true,
    election_office_phone: '(334) 242-7210',
    election_office_email: null,
    election_office_address: 'PO Box 5616, Montgomery, AL 36103',
    requirements: 'Must be a U.S. citizen, Alabama resident, and at least 18 by Election Day. Photo ID required to vote.',
  },
  {
    abbr: 'AK',
    jurisdictionSlug: 'alaska',
    election_office_name: 'Alaska Division of Elections',
    registration_url: 'https://voterregistration.alaska.gov/',
    registration_status_url: 'https://myvoterinformation.alaska.gov/',
    has_online_registration: true,
    ballot_tracking_url: 'https://myvoterinformation.alaska.gov/',
    has_ballot_tracking: true,
    election_office_phone: '(907) 276-4467',
    election_office_email: 'elections@alaska.gov',
    election_office_address: '240 Main Street Suite 401, Juneau, AK 99801',
    requirements: 'Must be a U.S. citizen, Alaska resident, and at least 18 by Election Day. No ID required to register by mail.',
  },
  {
    abbr: 'AZ',
    jurisdictionSlug: 'arizona',
    election_office_name: 'Arizona Secretary of State — Elections Division',
    registration_url: 'https://servicearizona.com/voterRegistration',
    registration_status_url: 'https://my.arizona.vote/voterRegistration/registrationStatusStep1.do',
    has_online_registration: true,
    ballot_tracking_url: 'https://my.arizona.vote/',
    has_ballot_tracking: true,
    election_office_phone: '(602) 542-8683',
    election_office_email: 'elections@azsos.gov',
    election_office_address: '1700 W Washington St, Floor 7, Phoenix, AZ 85007',
    requirements: 'Must be a U.S. citizen, Arizona resident, and at least 18 by Election Day. Proof of citizenship required to register.',
  },
  {
    abbr: 'AR',
    jurisdictionSlug: 'arkansas',
    election_office_name: 'Arkansas Secretary of State — Elections Division',
    registration_url: 'https://www.sos.arkansas.gov/elections/voter-information/voter-registration-information',
    registration_status_url: 'https://www.voterview.ar-nova.org/VoterView',
    has_online_registration: false,
    ballot_tracking_url: null,
    has_ballot_tracking: false,
    election_office_phone: '(501) 682-5070',
    election_office_email: 'elections@sos.arkansas.gov',
    election_office_address: '500 Woodlane St Suite 256, Little Rock, AR 72201',
    requirements: 'Must be a U.S. citizen, Arkansas resident, and at least 18 by Election Day. Photo ID required to vote.',
  },
  {
    abbr: 'CA',
    jurisdictionSlug: 'california',
    election_office_name: 'California Secretary of State — Elections Division',
    registration_url: 'https://registertovote.ca.gov/',
    registration_status_url: 'https://voterstatus.sos.ca.gov/',
    has_online_registration: true,
    ballot_tracking_url: 'https://www.sos.ca.gov/elections/ballot-status/',
    has_ballot_tracking: true,
    election_office_phone: '(916) 657-2166',
    election_office_email: null,
    election_office_address: '1500 11th Street, Sacramento, CA 95814',
    requirements: 'Must be a U.S. citizen, California resident, and at least 18 by Election Day. No ID required if registered.',
  },
  {
    abbr: 'CO',
    jurisdictionSlug: 'colorado',
    election_office_name: 'Colorado Secretary of State — Elections Division',
    registration_url: 'https://www.sos.state.co.us/voter/pages/pub/home.xhtml',
    registration_status_url: 'https://www.sos.state.co.us/voter/pages/pub/home.xhtml',
    has_online_registration: true,
    ballot_tracking_url: 'https://ballottrax.coloradosos.gov/voter/',
    has_ballot_tracking: true,
    election_office_phone: '(303) 894-2200',
    election_office_email: 'elections@coloradosos.gov',
    election_office_address: '1700 Broadway Suite 550, Denver, CO 80290',
    requirements: 'Must be a U.S. citizen, Colorado resident, and at least 18 by Election Day. All registered voters receive a mail ballot.',
  },
  {
    abbr: 'CT',
    jurisdictionSlug: 'connecticut',
    election_office_name: 'Connecticut Secretary of the State — Elections Division',
    registration_url: 'https://voterregistration.ct.gov/OLVR/welcome.do',
    registration_status_url: 'https://portaldir.ct.gov/sots/LookUp.aspx',
    has_online_registration: true,
    ballot_tracking_url: 'https://portaldir.ct.gov/sots/LookUp.aspx',
    has_ballot_tracking: true,
    election_office_phone: '(860) 509-6100',
    election_office_email: 'elections@ct.gov',
    election_office_address: '165 Capitol Avenue, Hartford, CT 06106',
    requirements: 'Must be a U.S. citizen, Connecticut resident, and at least 18 by Election Day. Same-day registration available.',
  },
  {
    abbr: 'DE',
    jurisdictionSlug: 'delaware',
    election_office_name: 'Delaware Department of Elections',
    registration_url: 'https://ivote.de.gov/VoterView',
    registration_status_url: 'https://ivote.de.gov/VoterView',
    has_online_registration: true,
    ballot_tracking_url: 'https://ivote.de.gov/VoterView',
    has_ballot_tracking: true,
    election_office_phone: '(302) 739-4277',
    election_office_email: 'elections.smyrna@delaware.gov',
    election_office_address: '905 S. Governors Avenue Suite 170, Dover, DE 19904',
    requirements: 'Must be a U.S. citizen, Delaware resident, and at least 18 by Election Day.',
  },
  {
    abbr: 'FL',
    jurisdictionSlug: 'florida',
    election_office_name: 'Florida Division of Elections',
    registration_url: 'https://registertovoteflorida.gov/',
    registration_status_url: 'https://registration.elections.myflorida.com/CheckVoterStatus',
    has_online_registration: true,
    ballot_tracking_url: 'https://registration.elections.myflorida.com/TrackVoterBallot',
    has_ballot_tracking: true,
    election_office_phone: '(850) 245-6200',
    election_office_email: 'elections@dos.myflorida.com',
    election_office_address: 'R.A. Gray Building, 500 S. Bronough Street, Tallahassee, FL 32399',
    requirements: 'Must be a U.S. citizen, Florida resident, and at least 18 by Election Day. Photo ID required to vote.',
  },
  {
    abbr: 'GA',
    jurisdictionSlug: 'georgia',
    election_office_name: 'Georgia Secretary of State — Elections Division',
    registration_url: 'https://registertovote.sos.ga.gov/',
    registration_status_url: 'https://mvp.sos.ga.gov/',
    has_online_registration: true,
    ballot_tracking_url: 'https://www.ballottrax.net/voter/',
    has_ballot_tracking: true,
    election_office_phone: '(404) 656-2871',
    election_office_email: 'elections@sos.ga.gov',
    election_office_address: '214 State Capitol, Atlanta, GA 30334',
    requirements: 'Must be a U.S. citizen, Georgia resident, and at least 18 by Election Day. Photo ID required to vote.',
  },
  {
    abbr: 'HI',
    jurisdictionSlug: 'hawaii',
    election_office_name: 'Hawaii Office of Elections',
    registration_url: 'https://olvr.hawaii.gov/',
    registration_status_url: 'https://olvr.hawaii.gov/',
    has_online_registration: true,
    ballot_tracking_url: 'https://ballotstatus.hawaii.gov/',
    has_ballot_tracking: true,
    election_office_phone: '(808) 453-8683',
    election_office_email: 'elections@hawaii.gov',
    election_office_address: '802 Lehua Avenue, Pearl City, HI 96782',
    requirements: 'Must be a U.S. citizen, Hawaii resident, and at least 18 by Election Day. All registered voters receive a mail ballot.',
  },
  {
    abbr: 'ID',
    jurisdictionSlug: 'idaho',
    election_office_name: 'Idaho Secretary of State — Elections Division',
    registration_url: 'https://elections.sos.idaho.gov/ElectionLink/VoterRegistration/VoterRegistrationSearch.aspx',
    registration_status_url: 'https://elections.sos.idaho.gov/ElectionLink/VoterRegistration/VoterRegistrationSearch.aspx',
    has_online_registration: false,
    ballot_tracking_url: null,
    has_ballot_tracking: false,
    election_office_phone: '(208) 334-2852',
    election_office_email: 'sos@sos.idaho.gov',
    election_office_address: 'PO Box 83720, Boise, ID 83720',
    requirements: 'Must be a U.S. citizen, Idaho resident, and at least 18 by Election Day. Same-day registration available at polls.',
  },
  {
    abbr: 'IL',
    jurisdictionSlug: 'illinois',
    election_office_name: 'Illinois State Board of Elections',
    registration_url: 'https://www.illinoisvoter.com/',
    registration_status_url: 'https://www.illinoisvoter.com/',
    has_online_registration: true,
    ballot_tracking_url: 'https://www.illinoisvoter.com/',
    has_ballot_tracking: true,
    election_office_phone: '(217) 782-4141',
    election_office_email: null,
    election_office_address: '2329 S. MacArthur Blvd, Springfield, IL 62704',
    requirements: 'Must be a U.S. citizen, Illinois resident, and at least 18 by Election Day. Same-day registration available.',
  },
  {
    abbr: 'IN',
    jurisdictionSlug: 'indiana',
    election_office_name: 'Indiana Election Division',
    registration_url: 'https://indianavoters.in.gov/',
    registration_status_url: 'https://indianavoters.in.gov/',
    has_online_registration: true,
    ballot_tracking_url: 'https://indianavoters.in.gov/',
    has_ballot_tracking: true,
    election_office_phone: '(317) 232-3939',
    election_office_email: 'ied@iec.in.gov',
    election_office_address: '302 W. Washington Street Rm E204, Indianapolis, IN 46204',
    requirements: 'Must be a U.S. citizen, Indiana resident, and at least 18 by Election Day. Photo ID required to vote.',
  },
  {
    abbr: 'IA',
    jurisdictionSlug: 'iowa',
    election_office_name: 'Iowa Secretary of State — Elections Division',
    registration_url: 'https://sos.iowa.gov/elections/voterinformation/voterregistration.html',
    registration_status_url: 'https://sos.iowa.gov/elections/voterinformation/voterregistration.html',
    has_online_registration: true,
    ballot_tracking_url: null,
    has_ballot_tracking: false,
    election_office_phone: '(515) 281-0145',
    election_office_email: 'sos@iowa.gov',
    election_office_address: 'Lucas State Office Building, 321 E 12th Street, Des Moines, IA 50319',
    requirements: 'Must be a U.S. citizen, Iowa resident, and at least 18 by Election Day. Photo ID required to vote.',
  },
  {
    abbr: 'KS',
    jurisdictionSlug: 'kansas',
    election_office_name: 'Kansas Secretary of State — Elections Division',
    registration_url: 'https://www.sos.ks.gov/elections/elections_vr.aspx',
    registration_status_url: 'https://myvoteinfo.voteks.org/VoterView',
    has_online_registration: true,
    ballot_tracking_url: 'https://myvoteinfo.voteks.org/VoterView',
    has_ballot_tracking: true,
    election_office_phone: '(785) 296-4561',
    election_office_email: 'sos@sos.ks.gov',
    election_office_address: '120 SW 10th Avenue, Topeka, KS 66612',
    requirements: 'Must be a U.S. citizen, Kansas resident, and at least 18 by Election Day. Photo ID required to vote.',
  },
  {
    abbr: 'KY',
    jurisdictionSlug: 'kentucky',
    election_office_name: 'Kentucky State Board of Elections',
    registration_url: 'https://vrsws.sos.ky.gov/ovrweb/',
    registration_status_url: 'https://vrsws.sos.ky.gov/voterQuery/',
    has_online_registration: true,
    ballot_tracking_url: null,
    has_ballot_tracking: false,
    election_office_phone: '(502) 573-7100',
    election_office_email: null,
    election_office_address: '140 Walnut Street, Frankfort, KY 40601',
    requirements: 'Must be a U.S. citizen, Kentucky resident, and at least 18 by Election Day. Photo ID required to vote.',
  },
  {
    abbr: 'LA',
    jurisdictionSlug: 'louisiana',
    election_office_name: 'Louisiana Secretary of State — Elections Division',
    registration_url: 'https://www.laaccess.sos.la.gov/',
    registration_status_url: 'https://voterportal.sos.la.gov/',
    has_online_registration: true,
    ballot_tracking_url: 'https://voterportal.sos.la.gov/BallotTracking',
    has_ballot_tracking: true,
    election_office_phone: '(225) 922-0900',
    election_office_email: null,
    election_office_address: '8585 Archives Avenue, Baton Rouge, LA 70809',
    requirements: 'Must be a U.S. citizen, Louisiana resident, and at least 18 by Election Day. Photo ID required to vote.',
  },
  {
    abbr: 'ME',
    jurisdictionSlug: 'maine',
    election_office_name: 'Maine Secretary of State — Division of Elections',
    registration_url: 'https://www.maine.gov/sos/cec/elec/voter-info/voterregtool.html',
    registration_status_url: 'https://www.maine.gov/sos/cec/elec/voter-info/voterregtool.html',
    has_online_registration: true,
    ballot_tracking_url: null,
    has_ballot_tracking: false,
    election_office_phone: '(207) 624-7736',
    election_office_email: 'sos.office@maine.gov',
    election_office_address: '101 State House Station, Augusta, ME 04333',
    requirements: 'Must be a U.S. citizen, Maine resident, and at least 18 by Election Day. Same-day registration available.',
  },
  {
    abbr: 'MD',
    jurisdictionSlug: 'maryland',
    election_office_name: 'Maryland State Board of Elections',
    registration_url: 'https://voterservices.elections.maryland.gov/OnlineVoterRegistration/InstructionsStep1',
    registration_status_url: 'https://voterservices.elections.maryland.gov/VoterSearch',
    has_online_registration: true,
    ballot_tracking_url: 'https://voterservices.elections.maryland.gov/BallotSearch',
    has_ballot_tracking: true,
    election_office_phone: '(410) 269-2840',
    election_office_email: 'elections.info@maryland.gov',
    election_office_address: '151 West Street Suite 200, Annapolis, MD 21401',
    requirements: 'Must be a U.S. citizen, Maryland resident, and at least 18 by Election Day. Same-day registration available.',
  },
  {
    abbr: 'MA',
    jurisdictionSlug: 'massachusetts',
    election_office_name: 'Massachusetts Secretary of the Commonwealth — Elections Division',
    registration_url: 'https://www.sec.state.ma.us/ovr/',
    registration_status_url: 'https://www.sec.state.ma.us/VoterRegistrationSearch/',
    has_online_registration: true,
    ballot_tracking_url: 'https://www.sec.state.ma.us/WhereDoIVoteMA/',
    has_ballot_tracking: true,
    election_office_phone: '(617) 727-2828',
    election_office_email: null,
    election_office_address: 'One Ashburton Place, Boston, MA 02108',
    requirements: 'Must be a U.S. citizen, Massachusetts resident, and at least 18 by Election Day. Same-day registration available.',
  },
  {
    abbr: 'MI',
    jurisdictionSlug: 'michigan',
    election_office_name: 'Michigan Secretary of State — Bureau of Elections',
    registration_url: 'https://mvic.sos.state.mi.us/RegisterVoter',
    registration_status_url: 'https://mvic.sos.state.mi.us/',
    has_online_registration: true,
    ballot_tracking_url: 'https://mvic.sos.state.mi.us/Voter/Index',
    has_ballot_tracking: true,
    election_office_phone: '(517) 335-3234',
    election_office_email: null,
    election_office_address: '430 W. Allegan Street, Lansing, MI 48918',
    requirements: 'Must be a U.S. citizen, Michigan resident, and at least 18 by Election Day. Same-day registration available.',
  },
  {
    abbr: 'MN',
    jurisdictionSlug: 'minnesota',
    election_office_name: 'Minnesota Secretary of State — Elections Division',
    registration_url: 'https://mnvotes.sos.state.mn.us/VoterRegistration/VoterRegistrationMain.aspx',
    registration_status_url: 'https://mnvotes.sos.state.mn.us/VoterStatus.aspx',
    has_online_registration: true,
    ballot_tracking_url: 'https://mnvotes.sos.state.mn.us/AbsenteeBallotStatus.aspx',
    has_ballot_tracking: true,
    election_office_phone: '(651) 215-1440',
    election_office_email: null,
    election_office_address: '180 State Office Building, 100 Rev. Dr. Martin Luther King Jr. Blvd, Saint Paul, MN 55155',
    requirements: 'Must be a U.S. citizen, Minnesota resident, and at least 18 by Election Day. Same-day registration available at polls.',
  },
  {
    abbr: 'MS',
    jurisdictionSlug: 'mississippi',
    election_office_name: 'Mississippi Secretary of State — Elections Division',
    registration_url: 'https://www.sos.ms.gov/elections-voting/voter-registration-information',
    registration_status_url: 'https://www.msegov.com/sos/voter_registration/AreYouRegistered',
    has_online_registration: false,
    ballot_tracking_url: null,
    has_ballot_tracking: false,
    election_office_phone: '(601) 576-2550',
    election_office_email: 'elections@sos.ms.gov',
    election_office_address: '125 S. Congress Street Suite 1225, Jackson, MS 39201',
    requirements: 'Must be a U.S. citizen, Mississippi resident, and at least 18 by Election Day. Photo ID required to vote.',
  },
  {
    abbr: 'MO',
    jurisdictionSlug: 'missouri',
    election_office_name: 'Missouri Secretary of State — Elections Division',
    registration_url: 'https://www.sos.mo.gov/elections/goVoteMissouri/register.aspx',
    registration_status_url: 'https://voteroutreach.sos.mo.gov/vat/vat.htm',
    has_online_registration: true,
    ballot_tracking_url: null,
    has_ballot_tracking: false,
    election_office_phone: '(573) 751-2301',
    election_office_email: 'elections@sos.mo.gov',
    election_office_address: '600 W. Main Street Room 324, Jefferson City, MO 65101',
    requirements: 'Must be a U.S. citizen, Missouri resident, and at least 18 by Election Day. Photo ID required to vote.',
  },
  {
    abbr: 'MT',
    jurisdictionSlug: 'montana',
    election_office_name: 'Montana Secretary of State — Elections Bureau',
    registration_url: 'https://app.mt.gov/voterinfo/',
    registration_status_url: 'https://app.mt.gov/voterinfo/',
    has_online_registration: true,
    ballot_tracking_url: 'https://app.mt.gov/voterinfo/',
    has_ballot_tracking: true,
    election_office_phone: '(406) 444-4732',
    election_office_email: 'sos@mt.gov',
    election_office_address: 'PO Box 202801, Helena, MT 59620',
    requirements: 'Must be a U.S. citizen, Montana resident, and at least 18 by Election Day. Same-day registration available.',
  },
  {
    abbr: 'NE',
    jurisdictionSlug: 'nebraska',
    election_office_name: 'Nebraska Secretary of State — Elections Division',
    registration_url: 'https://www.nebraska.gov/apps-sos-voter-registration/',
    registration_status_url: 'https://www.nebraska.gov/apps-sos-voter-registration/',
    has_online_registration: true,
    ballot_tracking_url: 'https://www.nebraska.gov/apps-sos-voter-registration/',
    has_ballot_tracking: true,
    election_office_phone: '(402) 471-2555',
    election_office_email: 'sos.elections@nebraska.gov',
    election_office_address: 'PO Box 94608, Lincoln, NE 68509',
    requirements: 'Must be a U.S. citizen, Nebraska resident, and at least 18 by Election Day. Photo ID required to vote.',
  },
  {
    abbr: 'NV',
    jurisdictionSlug: 'nevada',
    election_office_name: 'Nevada Secretary of State — Elections Division',
    registration_url: 'https://www.nvsos.gov/sosvoterservices/Registration/step1.aspx',
    registration_status_url: 'https://www.nvsos.gov/sosvoterservices/Registration/step1.aspx',
    has_online_registration: true,
    ballot_tracking_url: 'https://www.nvsos.gov/sosvoterservices/Ballots/MailBallotStatus.aspx',
    has_ballot_tracking: true,
    election_office_phone: '(775) 684-5705',
    election_office_email: 'nvsos@sos.nv.gov',
    election_office_address: '101 N. Carson Street Suite 3, Carson City, NV 89701',
    requirements: 'Must be a U.S. citizen, Nevada resident, and at least 18 by Election Day. Same-day registration available.',
  },
  {
    abbr: 'NH',
    jurisdictionSlug: 'new-hampshire',
    election_office_name: 'New Hampshire Secretary of State — Elections Division',
    registration_url: 'https://www.sos.nh.gov/elections/voters/register-vote',
    registration_status_url: 'https://app.sos.nh.gov/voterInformation',
    has_online_registration: false,
    ballot_tracking_url: null,
    has_ballot_tracking: false,
    election_office_phone: '(603) 271-3242',
    election_office_email: 'elections@sos.nh.gov',
    election_office_address: 'State House Room 204, Concord, NH 03301',
    requirements: 'Must be a U.S. citizen, New Hampshire resident, and at least 18 by Election Day. Same-day registration available at polls.',
  },
  {
    abbr: 'NJ',
    jurisdictionSlug: 'new-jersey',
    election_office_name: 'New Jersey Division of Elections',
    registration_url: 'https://voter.svrs.nj.gov/register',
    registration_status_url: 'https://voter.svrs.nj.gov/registration-check',
    has_online_registration: true,
    ballot_tracking_url: 'https://voter.svrs.nj.gov/ballot-status',
    has_ballot_tracking: true,
    election_office_phone: '(609) 292-3760',
    election_office_email: null,
    election_office_address: 'PO Box 304, Trenton, NJ 08625',
    requirements: 'Must be a U.S. citizen, New Jersey resident, and at least 18 by Election Day.',
  },
  {
    abbr: 'NM',
    jurisdictionSlug: 'new-mexico',
    election_office_name: 'New Mexico Secretary of State — Bureau of Elections',
    registration_url: 'https://portal.sos.state.nm.us/OVR/WebPages/InstructionsStep1.aspx',
    registration_status_url: 'https://voterview.sos.state.nm.us/WebPages/PublicSiteSearch.aspx',
    has_online_registration: true,
    ballot_tracking_url: 'https://voterview.sos.state.nm.us/WebPages/BallotSearch.aspx',
    has_ballot_tracking: true,
    election_office_phone: '(505) 827-3600',
    election_office_email: 'elections.sos@state.nm.us',
    election_office_address: '325 Don Gaspar Suite 300, Santa Fe, NM 87501',
    requirements: 'Must be a U.S. citizen, New Mexico resident, and at least 18 by Election Day. No ID required if registered.',
  },
  {
    abbr: 'NY',
    jurisdictionSlug: 'new-york',
    election_office_name: 'New York State Board of Elections',
    registration_url: 'https://www.elections.ny.gov/VoterRegister.html',
    registration_status_url: 'https://voterlookup.elections.ny.gov/',
    has_online_registration: true,
    ballot_tracking_url: 'https://absenteeballot.elections.ny.gov/',
    has_ballot_tracking: true,
    election_office_phone: '(518) 474-6220',
    election_office_email: null,
    election_office_address: '40 North Pearl Street Suite 5, Albany, NY 12207',
    requirements: 'Must be a U.S. citizen, New York resident, and at least 18 by Election Day.',
  },
  {
    abbr: 'NC',
    jurisdictionSlug: 'north-carolina',
    election_office_name: 'North Carolina State Board of Elections',
    registration_url: 'https://www.ncsbe.gov/registering/how-register',
    registration_status_url: 'https://vt.ncsbe.gov/RegLkup/',
    has_online_registration: true,
    ballot_tracking_url: 'https://vt.ncsbe.gov/BallotSearch/',
    has_ballot_tracking: true,
    election_office_phone: '(919) 814-0700',
    election_office_email: 'elections.sboe@ncsbe.gov',
    election_office_address: '430 N. Salisbury Street, Raleigh, NC 27603',
    requirements: 'Must be a U.S. citizen, North Carolina resident, and at least 18 by Election Day. Photo ID required to vote.',
  },
  {
    abbr: 'ND',
    jurisdictionSlug: 'north-dakota',
    election_office_name: 'North Dakota Secretary of State — Elections Division',
    registration_url: 'https://vip.sos.nd.gov/',
    registration_status_url: 'https://vip.sos.nd.gov/',
    has_online_registration: false,
    ballot_tracking_url: null,
    has_ballot_tracking: false,
    election_office_phone: '(701) 328-4146',
    election_office_email: 'sos@nd.gov',
    election_office_address: '600 E. Boulevard Avenue Dept 108, Bismarck, ND 58505',
    requirements: 'North Dakota has no voter registration. Must present ID at polls showing name, ND residential address, and date of birth.',
  },
  {
    abbr: 'OH',
    jurisdictionSlug: 'ohio',
    election_office_name: 'Ohio Secretary of State — Elections Division',
    registration_url: 'https://olvr.ohiosos.gov/',
    registration_status_url: 'https://voterlookup.ohiosos.gov/',
    has_online_registration: true,
    ballot_tracking_url: 'https://voterlookup.ohiosos.gov/',
    has_ballot_tracking: true,
    election_office_phone: '(614) 466-2585',
    election_office_email: 'voter@OhioSoS.gov',
    election_office_address: '22 N. Fourth Street, Columbus, OH 43215',
    requirements: 'Must be a U.S. citizen, Ohio resident, and at least 18 by Election Day. Photo ID required to vote.',
  },
  {
    abbr: 'OK',
    jurisdictionSlug: 'oklahoma',
    election_office_name: 'Oklahoma State Election Board',
    registration_url: 'https://www.ok.gov/elections/Voter_Info/Register_to_Vote/',
    registration_status_url: 'https://www.ok.gov/elections/Voter_Info/Online_Voter_Tool/',
    has_online_registration: true,
    ballot_tracking_url: null,
    has_ballot_tracking: false,
    election_office_phone: '(405) 521-2391',
    election_office_email: null,
    election_office_address: '2300 N. Lincoln Blvd Room B-6, Oklahoma City, OK 73105',
    requirements: 'Must be a U.S. citizen, Oklahoma resident, and at least 18 by Election Day. Photo ID required to vote.',
  },
  {
    abbr: 'OR',
    jurisdictionSlug: 'oregon',
    election_office_name: 'Oregon Secretary of State — Elections Division',
    registration_url: 'https://sos.oregon.gov/voting/Pages/register.aspx',
    registration_status_url: 'https://secure.sos.state.or.us/orestar/vr/showVoterSearch.do',
    has_online_registration: true,
    ballot_tracking_url: 'https://secure.sos.state.or.us/orestar/vr/showVoterSearch.do',
    has_ballot_tracking: true,
    election_office_phone: '(503) 986-1518',
    election_office_email: 'elections.sos@oregon.gov',
    election_office_address: '255 Capitol Street NE Suite 501, Salem, OR 97310',
    requirements: 'Must be a U.S. citizen, Oregon resident, and at least 18 by Election Day. Oregon is a vote-by-mail state.',
  },
  {
    abbr: 'PA',
    jurisdictionSlug: 'pennsylvania',
    election_office_name: 'Pennsylvania Department of State — Bureau of Elections',
    registration_url: 'https://www.vote.pa.gov/Register-to-Vote/Pages/Online-Voter-Registration.aspx',
    registration_status_url: 'https://www.vote.pa.gov/Register-to-Vote/Pages/Check-Voter-Registration.aspx',
    has_online_registration: true,
    ballot_tracking_url: 'https://www.vote.pa.gov/Voting-in-PA/Pages/Mail-and-Absentee-Ballot.aspx',
    has_ballot_tracking: true,
    election_office_phone: '(717) 787-5280',
    election_office_email: 'st-elec@pa.gov',
    election_office_address: '401 North Street Room 210, Harrisburg, PA 17120',
    requirements: 'Must be a U.S. citizen, Pennsylvania resident, and at least 18 by Election Day.',
  },
  {
    abbr: 'RI',
    jurisdictionSlug: 'rhode-island',
    election_office_name: 'Rhode Island Board of Elections',
    registration_url: 'https://vote.sos.ri.gov/Home/RegistertoVote',
    registration_status_url: 'https://vote.sos.ri.gov/Home/VoterSearch',
    has_online_registration: true,
    ballot_tracking_url: 'https://vote.sos.ri.gov/Home/AbsenteeBallotStatus',
    has_ballot_tracking: true,
    election_office_phone: '(401) 222-2340',
    election_office_email: 'boe@elections.ri.gov',
    election_office_address: '50 Branch Avenue, Providence, RI 02904',
    requirements: 'Must be a U.S. citizen, Rhode Island resident, and at least 18 by Election Day. Photo ID required for first-time voters.',
  },
  {
    abbr: 'SC',
    jurisdictionSlug: 'south-carolina',
    election_office_name: 'South Carolina State Election Commission',
    registration_url: 'https://www.scvotes.gov/how-register-vote',
    registration_status_url: 'https://info.scvotes.sc.gov/eng/voterinquiry/VoterInformationRequest.aspx',
    has_online_registration: true,
    ballot_tracking_url: 'https://info.scvotes.sc.gov/eng/AbsenteeBallotSearch/AbsenteeBallotSearch.aspx',
    has_ballot_tracking: true,
    election_office_phone: '(803) 734-9060',
    election_office_email: null,
    election_office_address: '1122 Lady Street Suite 500, Columbia, SC 29201',
    requirements: 'Must be a U.S. citizen, South Carolina resident, and at least 18 by Election Day. Photo ID required to vote.',
  },
  {
    abbr: 'SD',
    jurisdictionSlug: 'south-dakota',
    election_office_name: 'South Dakota Secretary of State — Elections Division',
    registration_url: 'https://vip.sdsos.gov/VIPLogin.aspx',
    registration_status_url: 'https://vip.sdsos.gov/VIPLogin.aspx',
    has_online_registration: true,
    ballot_tracking_url: null,
    has_ballot_tracking: false,
    election_office_phone: '(605) 773-3537',
    election_office_email: 'sdsos@state.sd.us',
    election_office_address: '500 E. Capitol Avenue Suite 204, Pierre, SD 57501',
    requirements: 'Must be a U.S. citizen, South Dakota resident, and at least 18 by Election Day. Photo ID required to vote.',
  },
  {
    abbr: 'TN',
    jurisdictionSlug: 'tennessee',
    election_office_name: 'Tennessee Secretary of State — Division of Elections',
    registration_url: 'https://ovr.govote.tn.gov/',
    registration_status_url: 'https://ovr.govote.tn.gov/',
    has_online_registration: true,
    ballot_tracking_url: null,
    has_ballot_tracking: false,
    election_office_phone: '(615) 741-7956',
    election_office_email: 'sos.elections@tn.gov',
    election_office_address: '312 Rosa L. Parks Avenue 6th Floor, Nashville, TN 37243',
    requirements: 'Must be a U.S. citizen, Tennessee resident, and at least 18 by Election Day. Photo ID required to vote.',
  },
  {
    abbr: 'TX',
    jurisdictionSlug: 'texas',
    election_office_name: 'Texas Secretary of State — Elections Division',
    registration_url: 'https://www.sos.texas.gov/elections/voter/reqvr.shtml',
    registration_status_url: 'https://teamrv-mvp.sos.texas.gov/MVP/mvp.do',
    has_online_registration: false,
    ballot_tracking_url: 'https://bbm.sos.texas.gov/',
    has_ballot_tracking: true,
    election_office_phone: '(800) 252-8683',
    election_office_email: 'elections@sos.texas.gov',
    election_office_address: 'P.O. Box 12697, Austin, TX 78711',
    requirements: 'Must be a U.S. citizen, Texas resident, and at least 18 by Election Day. Photo ID required to vote.',
  },
  {
    abbr: 'UT',
    jurisdictionSlug: 'utah',
    election_office_name: 'Utah Lieutenant Governor — Elections Office',
    registration_url: 'https://vote.utah.gov/vote/menu/index',
    registration_status_url: 'https://vote.utah.gov/vote/menu/index',
    has_online_registration: true,
    ballot_tracking_url: 'https://vote.utah.gov/vote/menu/index',
    has_ballot_tracking: true,
    election_office_phone: '(801) 538-1041',
    election_office_email: 'elections@utah.gov',
    election_office_address: 'PO Box 142325, Salt Lake City, UT 84114',
    requirements: 'Must be a U.S. citizen, Utah resident, and at least 18 by Election Day. Utah is a vote-by-mail state.',
  },
  {
    abbr: 'VT',
    jurisdictionSlug: 'vermont',
    election_office_name: 'Vermont Secretary of State — Elections Division',
    registration_url: 'https://mvp.vermont.gov/',
    registration_status_url: 'https://mvp.vermont.gov/',
    has_online_registration: true,
    ballot_tracking_url: 'https://mvp.vermont.gov/',
    has_ballot_tracking: true,
    election_office_phone: '(802) 828-2363',
    election_office_email: 'elections@sec.state.vt.us',
    election_office_address: '128 State Street, Montpelier, VT 05633',
    requirements: 'Must be a U.S. citizen, Vermont resident, and at least 18 by Election Day. Automatic voter registration. Same-day registration available.',
  },
  {
    abbr: 'VA',
    jurisdictionSlug: 'virginia',
    election_office_name: 'Virginia Department of Elections',
    registration_url: 'https://www.elections.virginia.gov/registration/how-to-register/',
    registration_status_url: 'https://www.elections.virginia.gov/registration/view-your-info/',
    has_online_registration: true,
    ballot_tracking_url: 'https://www.elections.virginia.gov/casting-a-ballot/absentee-voting/',
    has_ballot_tracking: true,
    election_office_phone: '(804) 864-8901',
    election_office_email: 'elect@elections.virginia.gov',
    election_office_address: '1100 Bank Street, Richmond, VA 23219',
    requirements: 'Must be a U.S. citizen, Virginia resident, and at least 18 by Election Day.',
  },
  {
    abbr: 'WA',
    jurisdictionSlug: 'washington',
    election_office_name: 'Washington Secretary of State — Elections Division',
    registration_url: 'https://voter.votewa.gov/WhereToVote.aspx',
    registration_status_url: 'https://voter.votewa.gov/WhereToVote.aspx',
    has_online_registration: true,
    ballot_tracking_url: 'https://voter.votewa.gov/WhereToVote.aspx',
    has_ballot_tracking: true,
    election_office_phone: '(800) 448-4881',
    election_office_email: 'elections@sos.wa.gov',
    election_office_address: 'PO Box 40229, Olympia, WA 98504',
    requirements: 'Must be a U.S. citizen, Washington resident, and at least 18 by Election Day. Washington is a vote-by-mail state.',
  },
  {
    abbr: 'WV',
    jurisdictionSlug: 'west-virginia',
    election_office_name: 'West Virginia Secretary of State — Elections Division',
    registration_url: 'https://ovr.sos.wv.gov/Register/Landing',
    registration_status_url: 'https://apps.sos.wv.gov/elections/voter/find.aspx',
    has_online_registration: true,
    ballot_tracking_url: null,
    has_ballot_tracking: false,
    election_office_phone: '(304) 558-6000',
    election_office_email: 'wvsos@wvsos.gov',
    election_office_address: 'Building 1 Suite 157-K, 1900 Kanawha Blvd East, Charleston, WV 25305',
    requirements: 'Must be a U.S. citizen, West Virginia resident, and at least 18 by Election Day. Photo ID required to vote.',
  },
  {
    abbr: 'WI',
    jurisdictionSlug: 'wisconsin',
    election_office_name: 'Wisconsin Elections Commission',
    registration_url: 'https://myvote.wi.gov/en-us/RegisterToVote',
    registration_status_url: 'https://myvote.wi.gov/en-us/VoterRegistration',
    has_online_registration: true,
    ballot_tracking_url: 'https://myvote.wi.gov/en-us/TrackMyBallot',
    has_ballot_tracking: true,
    election_office_phone: '(608) 261-2028',
    election_office_email: 'elections@wi.gov',
    election_office_address: '212 E. Washington Avenue 3rd Floor, Madison, WI 53703',
    requirements: 'Must be a U.S. citizen, Wisconsin resident, and at least 18 by Election Day. Photo ID required to vote. Same-day registration available.',
  },
  {
    abbr: 'WY',
    jurisdictionSlug: 'wyoming',
    election_office_name: 'Wyoming Secretary of State — Elections Division',
    registration_url: 'https://sos.wyo.gov/Elections/Docs/WYVoterReg.pdf',
    registration_status_url: 'https://sos.wyo.gov/Elections/VoterRegistration.aspx',
    has_online_registration: false,
    ballot_tracking_url: null,
    has_ballot_tracking: false,
    election_office_phone: '(307) 777-3573',
    election_office_email: 'sos@wyo.gov',
    election_office_address: '200 W. 24th Street, Cheyenne, WY 82002',
    requirements: 'Must be a U.S. citizen, Wyoming resident, and at least 18 by Election Day. Same-day registration available at polls.',
  },
  {
    abbr: 'DC',
    jurisdictionSlug: 'district-of-columbia',
    election_office_name: 'DC Board of Elections',
    registration_url: 'https://www.dcboe.org/Voters/Register-To-Vote/Register-Update-Voter-Registration',
    registration_status_url: 'https://www.dcboe.org/Voters/Register-To-Vote/Register-Update-Voter-Registration',
    has_online_registration: true,
    ballot_tracking_url: 'https://www.dcboe.org/Voters/Request-Absentee-Ballot',
    has_ballot_tracking: true,
    election_office_phone: '(202) 727-2525',
    election_office_email: 'dcboevotes@dc.gov',
    election_office_address: '1015 Half Street SE Suite 750, Washington, DC 20003',
    requirements: 'Must be a U.S. citizen, DC resident, and at least 18 by Election Day. Automatic voter registration. Same-day registration available.',
  },
];

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function importElectionServices(): Promise<void> {
  console.log('=== Import Election Services ===\n');
  console.log(`Processing ${ELECTION_SERVICES.length} state/jurisdiction records …\n`);

  let inserted = 0;
  let skipped = 0;

  for (const def of ELECTION_SERVICES) {
    process.stdout.write(`  ${def.abbr} — ${def.election_office_name} … `);

    // Resolve jurisdiction_id from the slug.
    const { data: jurisdiction, error: jErr } = await supabase
      .from('jurisdictions')
      .select('id')
      .eq('slug', def.jurisdictionSlug)
      .maybeSingle();

    if (jErr) {
      console.error(`ERROR (db): ${jErr.message}`);
      skipped++;
      continue;
    }

    if (!jurisdiction) {
      console.warn(`SKIP — jurisdiction not found (slug="${def.jurisdictionSlug}")`);
      skipped++;
      continue;
    }

    const record: ElectionServiceInsert = {
      jurisdiction_id: (jurisdiction as { id: string }).id,
      election_office_name: def.election_office_name,
      registration_url: def.registration_url,
      registration_status_url: def.registration_status_url,
      has_online_registration: def.has_online_registration,
      ballot_tracking_url: def.ballot_tracking_url,
      has_ballot_tracking: def.has_ballot_tracking,
      election_office_phone: def.election_office_phone,
      election_office_email: def.election_office_email,
      election_office_address: def.election_office_address,
      requirements: def.requirements,
    };

    const { error } = await supabase
      .from('election_services')
      .upsert(record, { onConflict: 'jurisdiction_id' });

    if (error) {
      console.error(`ERROR: ${error.message}`);
      skipped++;
    } else {
      console.log('OK');
      inserted++;
    }
  }

  console.log(
    `\n=== Completed. Inserted/updated: ${inserted}, skipped: ${skipped} ===`,
  );
}

importElectionServices().catch((err) => {
  console.error('\nFatal error:', err);
  process.exit(1);
});
